spring.application.name=FamilyWebApp

#profile 
spring.profiles.active=local
#spring.profiles.active=prod

# Spring Boot 
server.port=8083
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis ì¤ì 
mybatis.mapper-locations=classpath:mappers/**/*.xml

# multipart 업로드 용량 제한
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

spring.web.resources.static-locations=file:/app/static-override/,classpath:/static/
