
spring.datasource.url=jdbc:mariadb://100.91.231.32:3306/family?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=johnny1351
spring.datasource.password=johnjohn1!

#ㅇ
# \uD30C\uC77C \uC800\uC7A5 \uACBD\uB85C
storage.root=/data/trips
#storage.root=/home/pi/memories/storage
storage.url-prefix=/storage